// Package metadata only. Never regenerates or touches artwork.
import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const pkg = JSON.parse(await readFile(new URL('package.json', root), 'utf8'));
const original = JSON.parse(await readFile(new URL('images.json', root), 'utf8'));
const items = original.map(item => ({ ...item,
  uses: item.kind === 'standalone' ? ['image'] : ['frame', 'divider'],
  formats: ['svg', 'webp', 'png'].filter(format => item[format])
})).sort((a, b) => a.name.localeCompare(b.name, 'en'));
const base = `https://cdn.jsdelivr.net/npm/${pkg.name}@${pkg.version}/`;
await writeFile(new URL('lib/catalog.json', root), JSON.stringify(items, null, 2) + '\n');
await writeFile(new URL('lib/catalog.js', root), `// Generated by scripts/build-library.mjs from images.json and package.json.\nfunction freeze(value) { if (value && typeof value === 'object') { for (const child of Object.values(value)) freeze(child); Object.freeze(value); } return value; }\nexport const version = ${JSON.stringify(pkg.version)};\nexport const defaultAssetsBase = ${JSON.stringify(base)};\nexport const ornaments = freeze(${JSON.stringify(items)});\n`);
const union = values => values.map(value => JSON.stringify(value)).join(' | ');
const names = items.map(item => item.name);
const repeats = items.filter(item => item.kind === 'repeat-tile').map(item => item.name);
const whole = items.filter(item => item.kind === 'standalone').map(item => item.name);
const categories = [...new Set(items.flatMap(item => item.categories))].sort();
const declarations = `// Generated design/capability types; edit scripts/build-library.mjs.
export type DesignName = ${union(names)};
export type RepeatDesignName = ${union(repeats)};
export type WholeDesignName = ${union(whole)};
export type Category = ${union(categories)};
export type OrnamentUse = 'frame' | 'divider' | 'image';
export type Format = 'auto' | 'svg' | 'webp' | 'png';
export type Orientation = 'original' | 'horizontal' | 'vertical';
export interface RasterVariant {
  readonly png: string; readonly webp: string;
  readonly width: number; readonly height: number;
  readonly max_dimension?: number; readonly rendered_max_dimension?: number;
  readonly png_bytes: number; readonly webp_bytes: number;
}
export interface Asset extends RasterVariant {
  readonly svg?: string; readonly viewbox?: readonly number[];
  readonly variants: readonly RasterVariant[];
  readonly repeat_axis?: 'x' | 'y' | 'none';
  readonly repeat_ratio?: number; readonly slice_pixels?: number;
}
export interface Ornament extends Asset {
  readonly name: DesignName; readonly description: string;
  readonly categories: readonly Category[]; readonly subjects: readonly string[];
  readonly colors: readonly string[]; readonly facing: string; readonly composition: string;
  readonly kind: 'standalone' | 'repeat-tile'; readonly derivation: string;
  readonly uses: readonly OrnamentUse[]; readonly formats: readonly Exclude<Format, 'auto'>[];
  readonly components: Readonly<Partial<Record<'border_image' | 'corner' | 'rotated_tile' | 'reference_crop', Asset>>>;
  readonly border_image_slice_percent?: number; readonly reference?: string;
}
export interface RepeatOrnament extends Ornament {
  readonly name: RepeatDesignName; readonly kind: 'repeat-tile';
  readonly uses: readonly ('frame' | 'divider')[]; readonly repeat_axis: 'x' | 'y';
  readonly repeat_ratio: number; readonly border_image_slice_percent: number;
}
export interface WholeOrnament extends Ornament {
  readonly name: WholeDesignName; readonly kind: 'standalone';
  readonly uses: readonly 'image'[]; readonly repeat_axis: 'none';
}
export interface CommonOptions {
  size?: number; format?: Format; pixelRatio?: number; assetsBase?: string;
}
export interface FrameOptions extends CommonOptions { design: RepeatDesignName; }
export interface DividerOptions extends CommonOptions { design: RepeatDesignName; orientation?: Orientation; length?: number | string; }
export interface ImageOptions extends CommonOptions { design: WholeDesignName; alt?: string; }
export interface SelectionFilters {
  use?: OrnamentUse; categories?: readonly Category[]; subjects?: readonly string[];
  colors?: readonly string[]; query?: string;
}
export interface ResolvedOrnament {
  design: DesignName; use: OrnamentUse; axis?: 'x' | 'y'; size: number;
  className: string; style: Record<string, string>; attributes: Record<string, string>;
  asset: { path: string; url: string; format: Exclude<Format, 'auto'>; width: number; height: number; resolutionLimited: boolean; };
}
export interface OrnamentController<Options> {
  readonly element: HTMLElement;
  readonly configuration: ResolvedOrnament;
  update(options: Partial<Options>): OrnamentController<Options>;
  destroy(): void;
}
export declare const version: string;
export declare const defaultAssetsBase: string;
export declare const ornaments: readonly Ornament[];
export declare function getOrnament(name: RepeatDesignName): RepeatOrnament;
export declare function getOrnament(name: WholeDesignName): WholeOrnament;
export declare function getOrnament(name: string): Ornament;
export declare function findOrnaments(filters: SelectionFilters & { use: 'frame' | 'divider' }): RepeatOrnament[];
export declare function findOrnaments(filters: SelectionFilters & { use: 'image' }): WholeOrnament[];
export declare function findOrnaments(filters?: SelectionFilters): Ornament[];
export declare function resolveOrnament(use: 'frame', options: FrameOptions): ResolvedOrnament;
export declare function resolveOrnament(use: 'divider', options: DividerOptions): ResolvedOrnament;
export declare function resolveOrnament(use: 'image', options: ImageOptions): ResolvedOrnament;
export declare function createFrame(element: HTMLElement, options: FrameOptions): OrnamentController<FrameOptions>;
export declare function createDivider(element: HTMLElement, options: DividerOptions): OrnamentController<DividerOptions>;
export declare function createOrnamentImage(element: HTMLImageElement, options: ImageOptions): OrnamentController<ImageOptions>;
`;
await writeFile(new URL('lib/index.d.ts', root), declarations);
const customKey = String.fromCharCode(96) + '--' + '$' + '{string}' + String.fromCharCode(96);
await writeFile(new URL('lib/react.d.ts', root), `import type { CSSProperties, ForwardRefExoticComponent, RefAttributes, HTMLAttributes, ImgHTMLAttributes } from 'react';
import type { FrameOptions, DividerOptions, ImageOptions } from './index.js';
export type OrnamentStyle = CSSProperties & { [key: ${customKey}]: string | number | undefined };
export type OrnamentFrameProps = FrameOptions & Omit<HTMLAttributes<HTMLDivElement>, 'style' | 'dangerouslySetInnerHTML'> & { style?: OrnamentStyle };
export type OrnamentDividerProps = DividerOptions & Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'style' | 'dangerouslySetInnerHTML'> & { style?: OrnamentStyle; children?: never };
export type OrnamentImageProps = ImageOptions & Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'srcSet' | 'sizes' | 'height' | 'width' | 'alt' | 'children' | 'style' | 'dangerouslySetInnerHTML'> & { style?: OrnamentStyle; children?: never };
export declare const OrnamentFrame: ForwardRefExoticComponent<OrnamentFrameProps & RefAttributes<HTMLDivElement>>;
export declare const OrnamentDivider: ForwardRefExoticComponent<OrnamentDividerProps & RefAttributes<HTMLDivElement>>;
export declare const OrnamentImage: ForwardRefExoticComponent<OrnamentImageProps & RefAttributes<HTMLImageElement>>;
`);
console.error(`Built package metadata/types for ${items.length} designs at ${pkg.version}; artwork unchanged.`);
